name: Build and Upload Entire Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build project
        run: cargo build --release

      - name: Upload entire project directory
        uses: actions/upload-artifact@v4
        with:
          name: full-project
          path: ./
